/* 
 * Copyright 2017 José A. Pacheco Ondoño - joanpaon@gmail.com.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.japo.java.views;

import java.util.Properties;
import org.japo.java.controllers.Controller;
import org.japo.java.models.Model;
import org.japo.java.libraries.UtilesApp;

/**
 *
 * @author José A. Pacheco Ondoño - joanpaon@gmail.com
 */
public class View extends javax.swing.JFrame {

    // Fichero Propiedades
    public static final String FICHERO = "view.properties";

    // Referencias 
    private Model model;
    private Controller control;
    private Properties prpView;

    // Constructor
    public View() {
        // Inicializacion Anterior
        initBefore();

        // Creación Vista
        initComponents();

        // Inicializacion Posterior
        initAfter();
    }

    public Model getModel() {
        return model;
    }

    public void setModel(Model model) {
        this.model = model;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.ButtonGroup();
        pnlRotulo = new javax.swing.JPanel();
        lblRotulo = new javax.swing.JLabel();
        pnlAjuste = new javax.swing.JPanel();
        sldRojo = new javax.swing.JSlider();
        lblRojo = new javax.swing.JLabel();
        sldVerde = new javax.swing.JSlider();
        lblVerde = new javax.swing.JLabel();
        sldAzul = new javax.swing.JSlider();
        lblAzul = new javax.swing.JLabel();
        rbtFrente = new javax.swing.JRadioButton();
        lblFrente = new javax.swing.JLabel();
        rbtFondo = new javax.swing.JRadioButton();
        lblFondo = new javax.swing.JLabel();
        pnlControl = new javax.swing.JPanel();
        btnImportar = new javax.swing.JButton();
        btnExportar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión Color Rótulo");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnlRotulo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Rótulo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18))); // NOI18N

        lblRotulo.setBackground(java.awt.Color.white);
        lblRotulo.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        lblRotulo.setForeground(java.awt.Color.black);
        lblRotulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRotulo.setText("Texto de Prueba");
        lblRotulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        lblRotulo.setOpaque(true);

        javax.swing.GroupLayout pnlRotuloLayout = new javax.swing.GroupLayout(pnlRotulo);
        pnlRotulo.setLayout(pnlRotuloLayout);
        pnlRotuloLayout.setHorizontalGroup(
            pnlRotuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRotuloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRotulo, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlRotuloLayout.setVerticalGroup(
            pnlRotuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRotuloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRotulo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlAjuste.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ajustes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18))); // NOI18N

        sldRojo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        sldRojo.setMaximum(255);
        sldRojo.setValue(255);
        sldRojo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldRojoStateChanged(evt);
            }
        });

        lblRojo.setBackground(java.awt.Color.red);
        lblRojo.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        lblRojo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRojo.setText("255");
        lblRojo.setOpaque(true);

        sldVerde.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        sldVerde.setMaximum(255);
        sldVerde.setValue(255);
        sldVerde.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldVerdeStateChanged(evt);
            }
        });

        lblVerde.setBackground(java.awt.Color.green);
        lblVerde.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        lblVerde.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVerde.setText("255");
        lblVerde.setOpaque(true);

        sldAzul.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        sldAzul.setMaximum(255);
        sldAzul.setValue(255);
        sldAzul.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldAzulStateChanged(evt);
            }
        });

        lblAzul.setBackground(java.awt.Color.blue);
        lblAzul.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        lblAzul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAzul.setText("255");
        lblAzul.setOpaque(true);

        bg.add(rbtFrente);
        rbtFrente.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        rbtFrente.setSelected(true);
        rbtFrente.setText("Foreground");
        rbtFrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtFrenteActionPerformed(evt);
            }
        });

        lblFrente.setBackground(java.awt.Color.black);
        lblFrente.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        lblFrente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFrente.setOpaque(true);

        bg.add(rbtFondo);
        rbtFondo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        rbtFondo.setText("Background");
        rbtFondo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtFondoActionPerformed(evt);
            }
        });

        lblFondo.setBackground(java.awt.Color.white);
        lblFondo.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        lblFondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFondo.setOpaque(true);

        javax.swing.GroupLayout pnlAjusteLayout = new javax.swing.GroupLayout(pnlAjuste);
        pnlAjuste.setLayout(pnlAjusteLayout);
        pnlAjusteLayout.setHorizontalGroup(
            pnlAjusteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAjusteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAjusteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlAjusteLayout.createSequentialGroup()
                        .addComponent(sldRojo, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRojo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAjusteLayout.createSequentialGroup()
                        .addGroup(pnlAjusteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(sldAzul, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
                            .addComponent(sldVerde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlAjusteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAzul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAjusteLayout.createSequentialGroup()
                        .addComponent(rbtFrente, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblFrente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAjusteLayout.createSequentialGroup()
                        .addComponent(rbtFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAjusteLayout.setVerticalGroup(
            pnlAjusteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAjusteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAjusteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRojo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sldRojo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlAjusteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sldVerde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlAjusteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAzul, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sldAzul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlAjusteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFrente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtFrente))
                .addGap(18, 18, 18)
                .addGroup(pnlAjusteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtFondo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlAjusteLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblAzul, lblFrente, lblRojo, lblVerde, rbtFrente, sldAzul, sldRojo, sldVerde});

        pnlAjusteLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblFondo, rbtFondo});

        pnlControl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Controles", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18))); // NOI18N

        btnImportar.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btnImportar.setText("Importar");
        btnImportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarActionPerformed(evt);
            }
        });

        btnExportar.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btnExportar.setText("Exportar");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlControlLayout = new javax.swing.GroupLayout(pnlControl);
        pnlControl.setLayout(pnlControlLayout);
        pnlControlLayout.setHorizontalGroup(
            pnlControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlControlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnImportar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(btnExportar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );

        pnlControlLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnExportar, btnImportar});

        pnlControlLayout.setVerticalGroup(
            pnlControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControlLayout.createSequentialGroup()
                .addGroup(pnlControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImportar)
                    .addComponent(btnExportar))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlControl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlRotulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlAjuste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlRotulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAjuste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        control.procesarCierreVista(evt);
    }//GEN-LAST:event_formWindowClosing

    private void btnImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarActionPerformed
        control.procesarImportacion(evt);
    }//GEN-LAST:event_btnImportarActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        control.procesarExportacion(evt);
    }//GEN-LAST:event_btnExportarActionPerformed

    private void rbtFrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtFrenteActionPerformed
        control.procesarFrenteFondo(evt);
    }//GEN-LAST:event_rbtFrenteActionPerformed

    private void rbtFondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtFondoActionPerformed
        control.procesarFrenteFondo(evt);
    }//GEN-LAST:event_rbtFondoActionPerformed

    private void sldRojoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldRojoStateChanged
        control.procesarColor(evt);
    }//GEN-LAST:event_sldRojoStateChanged

    private void sldVerdeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldVerdeStateChanged
        control.procesarColor(evt);
    }//GEN-LAST:event_sldVerdeStateChanged

    private void sldAzulStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldAzulStateChanged
        control.procesarColor(evt);
    }//GEN-LAST:event_sldAzulStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg;
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnImportar;
    public javax.swing.JLabel lblAzul;
    public javax.swing.JLabel lblFondo;
    public javax.swing.JLabel lblFrente;
    public javax.swing.JLabel lblRojo;
    public javax.swing.JLabel lblRotulo;
    public javax.swing.JLabel lblVerde;
    private javax.swing.JPanel pnlAjuste;
    private javax.swing.JPanel pnlControl;
    private javax.swing.JPanel pnlRotulo;
    public javax.swing.JRadioButton rbtFondo;
    public javax.swing.JRadioButton rbtFrente;
    public javax.swing.JSlider sldAzul;
    public javax.swing.JSlider sldRojo;
    public javax.swing.JSlider sldVerde;
    // End of variables declaration//GEN-END:variables

    // Inicializacion Anterior
    private void initBefore() {
        // Crear Modelo
        model = new Model();

        // Crear Controlador
        control = new Controller(model, this);

        // Cargar Propiedades Vista
        prpView = UtilesApp.cargarPropiedades(FICHERO);

        // Restaurar Estado
        control.restaurarEstadoVista(this, prpView);
    }

    // Inicializacion Posterior
    private void initAfter() {
        // Modelo > Vista
        control.sincronizarModeloVista(model, this);

        // Enfocar Control Inicial
        btnImportar.requestFocus();
    }
}
